### ISSUE TITLE
suggestion for the message counter again xd

### ISSUE THREAD

**Issue by soudblox** [DZ-TM/Yagpdb.xyz#5]
ik dz is busy but just putting a suggestion here, make the leaderboard uh look better xddd since now its just simple;/

**Comment by DZ-TM** [comment]
That is intentional for ease of editing, you can already customise the message sent via lines 13-16 in the code (more specifically on line 16, 13-15 is used to do the database magic for finding out the top users)

I generally keep my embeds simple with at most (usually) a title and colour so it’s easier to find what you want to edit, for further questions on how you would edit the embed go to YAGPDB support server and type ;embed in the #testing channel.

**Comment by soudblox** [comment]
ah  ok
